
export const atributos = [
    { 
      name: "_id", 
      disabled: true, 
      type: "text", 
      required: true,
      regex: "[A-Za-z0-9 \\s]{0,}",
    },
    { 
      name: "proveedor", 
      disabled: false, 
      type: "text", 
      required: true,
      regex: "[A-Za-z0-9 \\s]{0,}",
    },
    { 
      name: "nombre", 
      disabled: false, 
      type: "text", 
      required: true,
      regex: "[A-Za-z0-9 \\s]{0,}",

    },
    { 
      name: "calle", 
      disabled: false, 
      type: "text", 
      required: true ,
      regex: "[A-Za-z0-9 \\s]{3,70}",
    },
    { 
      name: "colonia", 
      disabled: false, 
      type: "select", 
      required: true ,
      regex: "[A-Za-z0-9 \\s]{3,25}",
    },
    { 
      name: "pobla", 
      disabled: false, 
      type: "select", 
      required: true,
      regex: "[A-Za-z0-9 \\s]{3,25}",
    },
    { 
      name: "ciudad", 
      disabled: false, 
      type: "select", 
      required: true ,
      regex: "[A-Za-z0-9 \\s]{3,25}",
    },
    { 
      name: "estado", 
      disabled: false, 
      type: "select", 
      required: true ,
      regex: "[A-Za-z0-9 \\s]{3,25}",
    },
    { 
      name: "pais", 
      disabled: false, 
      type: "select", 
      required: true,
      regex: "[A-Za-z0-9 \\s]{3,25}",
    },
    { 
      name: "telefono", 
      disabled: false, 
      type: "text", 
      required: true,
      regex: "[0-9]{10,12}", 
    },
    { 
      name: "dias", 
      disabled: false, 
      type: "text", 
      required: true ,
      regex: "^([1-9][0-9][0-9][0-9]?|10000)",
    },
    { 
      name: "credito", 
      disabled: false, 
      type: "text", 
      required: true,
      regex: "[0-9](?:\\.\\d{1,2})?|100000000", 
    },
    { 
      name: "des1", 
      disabled: false, 
      type: "text", 
      required: true ,
      regex: "[0-9]?|100",
    },
    { 
      name: "contacto", 
      disabled: false, 
      type: "text", 
      required: true 
    },
    // { name: "alta", disabled: false, type: "text", required: true },
    { 
      name: "rfc", 
      disabled: false, 
      type: "text", 
      required: true,
      regex: "[A-Z0-9]{13,15}",
    },
    {
      name: "tipo",
      disabled: false,
      type: "select",
      required: true,
      options: [
        { tipo: 'Productos'},
        { tipo: 'Servicios'}
      ],
      regex: "[A-Za-z0-9 \\s]{0,}",
      label: "tipo",
    },
    { 
      name: "cp", 
      disabled: false, 
      type: "text", 
      required: true,
      regex: "[A-Za-z0-9 \\s]{0,}",
    },
    {
      name: "diasrevicion",
      disabled: false,
      type: "select",
      required: true,
      options: [
        { dia: "Lunes" },
        { dia: "Martes" },
        { dia: "Miercoles" },
        { dia: "Jueves" },
        { dia: "Viernes" },
      ],
      regex: "[A-Za-z0-9 \\s]{0,}",
      label: "dia",
    },
    { 
      name: "observ", 
      disabled: false, 
      type: "text", 
      required: true ,
      regex: "[A-Za-z0-9 \\s]{0,}",
    },
    {
      name: "zona",
      disabled: false,
      type: "select",
      required: true,
      api: "https://kapi-zonas.now.sh/api/zonas",
      regex: "[A-Za-z0-9 \\s]{0,}",
      label: "zona",
      value: "_id",
    },
    { 
      name: "url",
      disabled: false,
      type: "text",
      required: true,
      regex: "^(http:\\/\\/www\\.|https:\\/\\/www.|http:\\/\\/|https:\\/\\/)?[a-z0-9]+([\\-\\.]{1}[a-z0-9]+)\\.[a-z]{2,5}(:[0-9]{1,5})?(\\/.)?",
    },
    { 
      name: "mail", 
      disabled: false, 
      type: "text", 
      required: true ,
      regex:
        "^[a-zA-Z0-9.!#$%&'+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\\.[a-zA-Z0-9-]+)",
    },
    { 
      name: "saldo",
      disabled: false, 
      type: "text", 
      required: true,
      regex: "[A-Za-z0-9 \\s]{0,}" 
    },
    { 
      name: "usuario", 
      disabled: false, 
      type: "text", 
      required: true,
      regex: "[A-Za-z0-9 \\s]{0,}",
    },
    // { name: "usuHora", disabled: false, type: "text", required: true },
    // { name: "usuFech", disabled: false, type: "text", required: true },
  ];