import {api_clasificacionclientes} from '../../../utils/apis';
import {api_personal} from '../../../utils/apis';
import {api_kitelementos} from '../../../utils/apis';

export const subCatalogues = [
    {
      component: {
        api: api_clasificacionclientes,
        catalogo: "clasificacionclientes",
        attrs: {
          _id: true,
          clasificacion: true,
          descrip: true,
          usuario: true,
          usufecha: true,
          usuhora: true,
        },
        id: "clasificacionclientes",
      },
      title: "Clasificación de Clientes",
      selected: true,
    },
    {
      component: {
        api: api_personal,
        catalogo: "personal",
        attrs: {
          _id: true,
          empleado: true,
          tipo: true,
          nombre: true,
          usuario: true,
          usufecha: true,
          usuhora: true,
          horaentrada: true,
          horasalida: true,
          foto: true,
          pais: true,
          cp: true,
          calle: true,
          numeroexterior: true,
          numerointerior: true,
          colonia: true,
          poblacion: true,
          ciudad: true,
          estado: true,
          telefono: true,
          rfc: true,
          curp: true,
          numeroseguridadsocial: true,
          departamento: true,
          puesto: true,
          banco: true,
          cuentabanco: true,
          inicioactividades: true,
          tipocontrato: true,
          tipojornada: true,
          pagodesalario: true,
          salariobasecotizacion: true,
          riesgopuesto: true,
          estadonomina: true,
          antiguedad: true,
          correo: true,
          salariodiariointegrado: true,
          observaciones: true,
          regimencontractual: true,
        },
        id: "Personal",
      },
      title: "Personal",
      selected: false,
    },
    {
      component: {
        api: api_kitelementos,
        catalogo: "kitelementos",
        attrs: {
          _id: true,
          articulo: true,
          componente: true,
          cantidad: true,
          almacen: true,
          observ: true,
          idpartida: true,
          usuario: true,
          usufecha: true,
          usuhora: true,
        },
        id: "kitelementos",
      },
      title: "Kitelementos",
      selected: false,
    },
  ];