export const TOGGLE_MODAL = "TOGGLE_MODAL";
export const EDIT = "EDIT";
export const UPDATE_VISIBLE_COLUMNS = "UPDATE_VISIBLE_COLUMNS";
export const UPDATE_VISIBLE_CONTACT = "UPDATE_VISIBLE_CONTACT";
export const UPDATE_VISIBLE_PROVIDERS = "UPDATE_VISIBLE_PROVIDERS";

//

export const UPDATE_VISIBLE_PRODUCTS = "UPDATE_VISIBLE_PRODUCTS";

export const UPDATE_VISIBLE_FABRICANTES = "UPDATE_VISIBLE_FABRICANTES";

export const UPDATE_VISIBLECLAVES = "UPDATE_VISIBLECLAVES";

export const UPDATE_VISIBLE_IMPUESTOS = "UPDATE_VISIBLE_IMPUESTOS";

export const UPDATE_VISIBLE_LINEAS = "UPDATE_VISIBLE_LINEAS";

export const UPDATE_VISIBLEMARCAS = "UPDATE_VISIBLEMARCAS";
