export const TOGGLE_MODAL = "TOGGLE_MODAL";
export const EDIT = "EDIT";
export const UPDATE_VISIBLE_COLUMNS = "UPDATE_VISIBLE_COLUMNS";
export const UPDATE_VISIBLE_CONTACT = "UPDATE_VISIBLE_CONTACT";
export const UPDATE_VISIBLE_PROVIDERS = "UPDATE_VISIBLE_PROVIDERS";
export const UPDATE_VISIBLE_CLASIFICATION = "UPDATE_VISIBLE_CLASIFICATION";
