import { api_contactos } from "../../../utils/apis";

export const contacts = {
  component: {
    api: api_contactos,
    catalogo: "contactos_clientes_proveedores",
    attrs: {
      _id: true,
      uid: true,
      cliente: true,
      proveedor: true,
      nombre: true,
      puesto: true,
      email: true,
      telefono: true,
      celular: true,
      f_nacimiento: true,
    },
    inputs: [
      {
        name: "_id",
        disabled: true,
        type: "text",
        required: true,
        regex: "[A-Za-z0-9 \\s]{0,}",
      },
      {
        name: "uid",
        disabled: true,
        type: "text",
        required: true,
        regex: "[A-Za-z0-9 \\s]{0,}",
        label: "clasificacion",
      },
      {
        name: "cliente",
        disabled: true,
        type: "text",
        required: true,
        regex: "[A-Za-z0-9 \\s]{0,}",
      },
      {
        name: "proveedor",
        disabled: true,
        type: "text",
        required: true,
        regex: "[A-Za-z0-9 \\s]{0,}",
      },
      {
        name: "nombre",
        disabled: false,
        type: "text",
        required: true,
        regex: "[A-Za-z0-9 \\s]{0,}",
      },
      {
        name: "puesto",
        disabled: false,
        type: "text",
        required: true,
        regex: "[A-Za-z0-9 \\s]{0,}",
      },
      {
        name: "email",
        disabled: false,
        type: "text",
        required: true,
        regex: "[A-Za-z0-9 \\s]{0,}",
      },
      {
        name: "telefono",
        disabled: false,
        type: "number",
        required: true,
        regex: "[A-Za-z0-9 \\s]{0,}",
      },
      {
        name: "celular",
        disabled: false,
        type: "number",
        required: true,
        regex: "[A-Za-z0-9 \\s]{0,}",
      },
      {
        name: "f_nacimiento",
        disabled: false,
        type: "date",
        required: true,
        regex: "[A-Za-z0-9 \\s]{0,}",
      },
    ],
    id: "clasificacionclientes",
  },
  title: "Contactos",
  selected: false,
};
