export const atributosClientes = [
  "cliente", // opcional
  "nombre_fis", // requerido
  "calle", // requerido
  "colonia", // requerido
  "pobla", // requerido
  "ciudad", // requerido
  "estado", // requerido
  "pais", // requerido
  "telefono", // requerido
  "dias", // opcional
  "credito", // opcional
  "desc1", // opcional
  "rfc", // requerido
  "clasificacion", // requerido
  "contacto", // requerido
  "cobrador", // requerido
  "vend", // requerido
  "precio", // opcional
  "cp", // requerido
  "diasrevision", // requerido
  "observ", // requerido
  "zona", // requerido
  "correo", // requerido
  "url", // requerido
  "saldo", // opcional
  "usuario", // requerido
  "usuhora", // requerido
  "usufecha", // requerido
  "diascobro", // requerido
  "bloqueado", // opcional
  "web", // requerido
  "emailcobranza", // requerido
  "foto", // requerido
  "puntos", // opcional
  "recomendado", // requerido
  "numerointerior", // requerido
  "numeroexterior", // requerido
  "uso", // requerido
  "paiscomextrecep", // opcional
  "municipiocomextrecep", // opcional
  "localidadcomextrecep", // opcional
  "estadocomextrecep", // opcional
  "coloniacomextrecep", // opcional
  "residenciafiscal", // requerido
  "numregidtrib", // requerido
  "complementoexterior"
];
